
package com.sf.vas.mtnsms.soapartifacts.sendservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SendSms", targetNamespace = "http://www.csapi.org/wsdl/parlayx/sms/send/v2_2/interface")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SendSms {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.sf.vas.mtnsms.soapartifacts.sendservice.SendSmsResponse
     * @throws PolicyException_Exception
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "sendSmsResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", partName = "result")
    public SendSmsResponse sendSms(
        @WebParam(name = "sendSms", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", partName = "parameters")
        SendSms_Type parameters)
        throws PolicyException_Exception, ServiceException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns com.sf.vas.mtnsms.soapartifacts.sendservice.SendSmsLogoResponse
     * @throws PolicyException_Exception
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "sendSmsLogoResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", partName = "result")
    public SendSmsLogoResponse sendSmsLogo(
        @WebParam(name = "sendSmsLogo", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", partName = "parameters")
        SendSmsLogo parameters)
        throws PolicyException_Exception, ServiceException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns com.sf.vas.mtnsms.soapartifacts.sendservice.SendSmsRingtoneResponse
     * @throws PolicyException_Exception
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "sendSmsRingtoneResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", partName = "result")
    public SendSmsRingtoneResponse sendSmsRingtone(
        @WebParam(name = "sendSmsRingtone", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", partName = "parameters")
        SendSmsRingtone parameters)
        throws PolicyException_Exception, ServiceException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns com.sf.vas.mtnsms.soapartifacts.sendservice.GetSmsDeliveryStatusResponse
     * @throws PolicyException_Exception
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "getSmsDeliveryStatusResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", partName = "result")
    public GetSmsDeliveryStatusResponse getSmsDeliveryStatus(
        @WebParam(name = "getSmsDeliveryStatus", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local", partName = "parameters")
        GetSmsDeliveryStatus parameters)
        throws PolicyException_Exception, ServiceException_Exception
    ;

}
