
package com.sf.vas.mtnsms.soapartifacts.notification;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.sf.vas.mtnsms.jaxb.commonheadtypes.NotifySOAPHeader;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SmsNotification", targetNamespace = "http://www.csapi.org/wsdl/parlayx/sms/notification/v2_2/interface")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SmsNotification {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.sf.vas.sms.notifyartifacts.NotifySmsReceptionResponse
     */
    @WebMethod
    @WebResult(name = "notifySmsReceptionResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/notification/v2_2/local", partName = "result")
    public NotifySmsReceptionResponse notifySmsReception(
        @WebParam(name = "notifySmsReception", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/notification/v2_2/local", partName = "parameters")
        NotifySmsReception parameters,
        @WebParam(name = "NotifySOAPHeader", targetNamespace = "http://www.huawei.com.cn/schema/common/v2_1", header = true)
        NotifySOAPHeader header);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.sf.vas.sms.notifyartifacts.NotifySmsDeliveryReceiptResponse
     */
//    @WebMethod
//    @WebResult(name = "notifySmsDeliveryReceiptResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/notification/v2_2/local", partName = "result")
//    public NotifySmsDeliveryReceiptResponse notifySmsDeliveryReceipt(
//        @WebParam(name = "notifySmsDeliveryReceipt", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/notification/v2_2/local", partName = "parameters")
//        NotifySmsDeliveryReceipt parameters);
    
    @WebMethod
    @WebResult(name = "notifySmsDeliveryReceiptResponse", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/notification/v2_2/local", partName = "result")
    public NotifySmsDeliveryReceiptResponse notifySmsDeliveryReceipt(
        @WebParam(name = "notifySmsDeliveryReceipt", targetNamespace = "http://www.csapi.org/schema/parlayx/sms/notification/v2_2/local", partName = "parameters")
        NotifySmsDeliveryReceipt parameters,
        @WebParam(name = "NotifySOAPHeader", targetNamespace = "http://www.huawei.com.cn/schema/common/v2_1", header = true)
        NotifySOAPHeader header);    

}
