//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 04:01:29 PM WAT 
//


package com.sf.vas.mtnsms.jaxb.commonheadtypes;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sf.vas.sms.jaxb.commonheadtypes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RequestSOAPHeader_QNAME = new QName("http://www.huawei.com.cn/schema/common/v2_1", "RequestSOAPHeader");
    private final static QName _NotifySOAPHeader_QNAME = new QName("http://www.huawei.com.cn/schema/common/v2_1", "NotifySOAPHeader");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sf.vas.sms.jaxb.commonheadtypes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestSOAPHeader }
     * 
     */
    public RequestSOAPHeader createRequestSOAPHeader() {
        return new RequestSOAPHeader();
    }

    /**
     * Create an instance of {@link NotifySOAPHeader }
     * 
     */
    public NotifySOAPHeader createNotifySOAPHeader() {
        return new NotifySOAPHeader();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestSOAPHeader }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.huawei.com.cn/schema/common/v2_1", name = "RequestSOAPHeader")
    public JAXBElement<RequestSOAPHeader> createRequestSOAPHeader(RequestSOAPHeader value) {
        return new JAXBElement<RequestSOAPHeader>(_RequestSOAPHeader_QNAME, RequestSOAPHeader.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifySOAPHeader }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.huawei.com.cn/schema/common/v2_1", name = "NotifySOAPHeader")
    public JAXBElement<NotifySOAPHeader> createNotifySOAPHeader(NotifySOAPHeader value) {
        return new JAXBElement<NotifySOAPHeader>(_NotifySOAPHeader_QNAME, NotifySOAPHeader.class, null, value);
    }

}
